### ISSUE TITLE
Configuration error LoadError: cannot load such file -- chef/azure/chefhandlers/start_handler

### ISSUE THREAD

**Issue by JustinPullen** [chef-partners/azure-chef-extension#101]
I am running several Ubuntu 14.04 Machines on azure with this extension.

We added the extension to the machines though the azure portal about a year ago.  It worked but has always given back the status of installing in the azure portal.  

We had no problems besides the extension showing that it was Installing in the portal until today.

Our Team city server out of no where hit the error below when trying to run `chef-client` on one of the nodes.

```
[2015-12-10T21:29:13+00:00] FATAL: Configuration error LoadError: cannot load such file -- chef/azure/chefhandlers/start_handler
[2015-12-10T21:29:13+00:00] FATAL:   /etc/chef/client.rb:15:in `from_string'
[2015-12-10T21:29:13+00:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

I checked /etc/client.rb and nothing seemed off but it was hanging on the bellow lines.

```
#Add support to use chef Handlers for heartbeat and
#status reporting to Azure
require 'chef/azure/chefhandlers/start_handler'
require 'chef/azure/chefhandlers/report_handler'
require 'chef/azure/chefhandlers/exception_handler'

start_handlers << AzureExtension::StartHandler.new('/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2')
report_handlers << AzureExtension::ReportHandler.new('/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2')
exception_handlers << AzureExtension::ExceptionHandler.new('/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2')
```

I had to comment all the above lines out to have chef-client run properly.

I did check to see what version of the extension was on the machine.  I checked in /var/lib/waaget and found two folders in there `Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.2` and `Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2`

Our server reported running during each chef run `Starting Chef Client, version 11.16.4`  I found that strange so I ran `sh update.sh` under /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2.

The update just installed 11.16.4.2 again.  So I then ran `sh uninstall.sh` appeared successful.

I then changed directories to Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.2 and installed it with install.sh although it appears installed already.  

I check to see if my client.rb had updated links to log files and StartHandler but it was all still pointing to /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.16.4.2. and not /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.2. So I changed then to the new version hoping it would fix the issue. However it did not fix the issue. 

I attempted to run chef-client again but it displayed the same error as before.

```
[2015-12-10T21:29:13+00:00] FATAL: Configuration error LoadError: cannot load such file -- chef/azure/chefhandlers/start_handler
[2015-12-10T21:29:13+00:00] FATAL:   /etc/chef/client.rb:15:in `from_string'
[2015-12-10T21:29:13+00:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

The server now reports `Starting Chef Client, version 11.18.6`
I even tried disable.sh and enable.sh.  

Not sure where to troubleshoot next.

Seems odd that the client.rb was not updated to the new version and that the issue persisted even after uninstalling the older version and installing the newer one.  

Any guidance would be greatly appreciated. 

Thanks Justin P.

**Comment by JustinPullen** [comment]
I also noticed that my Cron is still referencing 11.16.4.2 so it was never updated.

**Comment by NimishaS** [comment]
@JustinPullen , when install.sh, update.sh etc scripts are executed from the VM itself, status is not reported back to Azure Portal. They are not meant to be run from the VM directly.
For now, you can uninstall the current extension and then install the latest extension. Please run the given command from `Azure Powershell CLI`:
```
#Uninstall current extension
$vmm = Get-AzureVM -Name "<vm-name>" -ServiceName "<cloud-service-name>"

$vmOb = Set-AzureVMExtension -VM $vmm -ExtensionName 'ChefClient' -Publisher ‘Chef.Bootstrap.WindowsAzure’ -Version '11.18' -Uninstall

Update-AzureVM -VM $vmOb.VM -Name "<vm-name>" -ServiceName "<cloud-service-name>"
```
Please check that `/etc/chef` folder is deleted and the extension folder inside `/var/lib/waagent` is also deleted. 

```
#Install new extension
$vmm = Get-AzureVM -Name "<vm-name>" -ServiceName "<cloud-service-name>"

$vmOb = Set-AzureVMExtension -VM $vmm -ExtensionName 'ChefClient' -Publisher ‘Chef.Bootstrap.WindowsAzure’ -Version '1210.12'

Update-AzureVM -VM $vmOb.VM -Name "<vm-name>" -ServiceName "<cloud-service-name>"
```

**Comment by JustinPullen** [comment]
I will Run this command shortly.

I did notice that the older version 11.18 is still in the azure UI When installing the extension when creating a VM in the portal.

**Comment by JustinPullen** [comment]
After running the following command on my VM It did remove the extension from /var/lib/waagent/ but did not remove /etc/chef all the files are still there including client.rb and validation.pem

```#Uninstall current extension
$vmm = Get-AzureVM -Name "<vm-name>" -ServiceName "<cloud-service-name>"

$vmOb = Set-AzureVMExtension -VM $vmm -ExtensionName 'ChefClient' -Publisher ‘Chef.Bootstrap.WindowsAzure’ -Version '11.18' -Uninstall

Update-AzureVM -VM $vmOb.VM -Name "<vm-name>" -ServiceName "<cloud-service-name>"```

**Comment by NimishaS** [comment]
@JustinPullen , this sounds like some issue. But to get you unblocked, can you please delete the `/etc/chef` directory manually and continue with the installation of new extension?

**Comment by JustinPullen** [comment]
I am looking into this again and continuing to trouble shoot issues. 

I am looking to install your extension on ASM and not ARM instances on azure.  I have done what you stated above but now can not install the extension any long.  Below is the command that I am using via azure cli but I am receiving an error 

azure vm extension set-chef XXXXX -c 'path/to/client.rb' -C '.path/to/valadation.pem' --version "1201.12"

I am receiving this error: `[Error: Could not find the extension with provider name space Chef.Bootstrap.WindowsAzure and type LinuxChefClient.]`

Does your extension support ASM instance any longer.  I do not see it in the list when I try to add an extension from the portal.  If it does what is the command that I need to run to install on my ASM instances.

Thanks.

**Comment by NimishaS** [comment]
@JustinPullen , sorry for such a delayed response. The version specified in your command should be `1210.12` and not `1201.12`

**Comment by jkerry** [comment]
I just ran into this on a fresh centos 7.2 install
