### ISSUE TITLE
 ARM Chef Extension issue JSON Escaping Keys not working

### ISSUE THREAD

**Issue by srakesh28** [chef-partners/azure-chef-extension#102]
I am trying to provision the Linux Chef Extension ARM template using ARM and I am unsuccessful. 
It worked with the classic portal. The issue seems to be with the validation key parameter in the ARM template
The classic portal expects a file name, whereas the ARM template expects a string. 
I have tried the template parameter with both validation key filepath and RSA key as well but the chef-client is unable to register. The chef-client fails to register to chef-server, and i believe it's  because it can't parse JSON escape keys. I tried the json parameter file and noticed that the validation key should have the entire contents of the .pem file with \n added. I used this json parameter and my .pem contents and provisioned the VM and chef extension failed to register. 

Process I followed is : 
1.  Launch the my template: https://github.com/srakesh28/azure-iaasv2-arm/blob/master/step2-linuxvm/azuredeploy-chefextention.json
2.  Provides all the chef parameters in the the portal. Here are sample values
3.   nodename : <nodename>
4.   Chef Server url : 
5.   Validation client name -
6.   Validation Key
7.   Json escape the contents of orgname-validator.pem
8.  Run the template.
9.  Server are deployed Chef Client is installed and I can see in Portal but Client does not register to Chef-server.

Thank you

**Comment by NimishaS** [comment]
@srakesh28 , there is an issue in parsing the `validation key` when provided from the portal. We are trying to work that out. 
You can use `Azure Powershell CLI` or `azure-xplat-cli` to create VM using ARM template. You need to convert `validation key` in proper format. For that use following commands:

Linux:
```
validation_key=$(sed ':a;N;$!ba;s/\n/\\n/g' ~/.chef/tstorgnztn-validator.pem)
echo $validation_key
```

Windows:
```
$validation_key = sed ':a;N;$!ba;s/\n/\\n/g' C:\Users\ali\.chef\tstorgnztn-validator.pem
$validation_key
```

Please refer https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage for creating VM with extension using ARM template. Steps are provided at the end of the link that I have shared.

**Comment by srakesh28** [comment]
Thanks I would suggest  if there is a way to just attach/upload a pfx file during process it will simplify this setup.

Thanks
 Rakesh Shah
408-391-9610

**Comment by NimishaS** [comment]
`validation_key` can now be passed in `Base64 encoded` format to avoid `JSON Escaping` issue. Please refer https://github.com/Azure/azure-quickstart-templates/blob/master/chef-json-parameters-linux-vm/azuredeploy.json#L69.

@srakesh28 please let us know if this resolves your issue

**Comment by Vasu1105** [comment]
@srakesh28 you can reopen this issue if you still facing the it.
