### ISSUE TITLE
autoUpdateClient=false being ignored

### ISSUE THREAD

**Issue by CaseyBurnsSv** [chef-partners/azure-chef-extension#123]
This happened last year, I just found this project today. This might be out of date, but thought its worth posting in case;

The Azure Plugin for Chef uninstalled our ChefClient Agent and left all of our FrontEnd VMs without the ChefClient installed.

It appears Azure attempted to upgrade the ChefClient -- even though we have autoUpdateClient set to false. Our Chef client plugin was 1210.12.4.1 -- on 20th Aug it appears it tried to upgrade to  1210.12.4.1000.

I can see in the logs that the uninstall did not respect autoUpdateClient = false and uninstalled the ChefClient.

It then executed install.cmd for 1210.12.4.1000 which did respect autoUpdateClient = false -- meaning that it did not install the ChefClient.

I have manually updated autoUpdateClient = true and ran the install.cmd and enable.cmd manually which appears to have fixed the problem.

**Comment by NimishaS** [comment]
@CaseyBurnsSv , this indeed was an issue with the older versions of the extension, but this has been resolved now. You can set `uninstallChefClient` flag `false` to avoid complete `chef-client` uninstall.  But this change has been introduced in release `1210.12.101.1000`(https://github.com/chef-partners/azure-chef-extension/blob/master/CHANGELOG.md#release-1210121011000-for-windows-20160204-and-1210121011000-for-ubuntu-20160212). So you need to switch to the latest versions of the extension.

**Comment by CaseyBurnsSv** [comment]
Thanks @NimishaS
