### ISSUE TITLE
Extension does not create client.rb, install fails

### ISSUE THREAD

**Issue by Rev68** [chef-partners/azure-chef-extension#125]
Using the chef-json-parameters-linux-vm quickstart template for ARM deployments, and chef fails to start, complaining that there is no /etc/chef/client.rb file. When I log into the server, I only see a file called 0.settings with all my parameters in the /etc/chef/ directory and nothing else.

Here's the CommandExecutionLog:
2016/04/20 23:05:44 Downloading plugin manifest: Chef.Bootstrap.WindowsAzure.LinuxChefClient from http://ardfepirv2sn3prdstr05.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure_LinuxChefClient_ussouth_manifest.xml
2016/04/20 23:05:44 Plugin server is: ardfepirv2sn3prdstr05.blob.core.windows.net
2016/04/20 23:05:45 Bundle URI = http://ardfepirv2sn3prdstr05.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__1210.12.102.1000
2016/04/20 23:05:45 Plugin bundlehttp://ardfepirv2sn3prdstr05.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__1210.12.102.1000downloaded successfully length = 70669
2016/04/20 23:05:45 Extracted http://ardfepirv2sn3prdstr05.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__1210.12.102.1000 to /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000
2016/04/20 23:05:45 Found RuntimeSettings for Chef.Bootstrap.WindowsAzure.LinuxChefClient V 1210.12.102.1000
2016/04/20 23:05:45 Spawned install.sh PID 1788
2016/04/20 23:06:55 installCommand completed.
2016/04/20 23:06:55 Installation completed for Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000
2016/04/20 23:06:55 Found RuntimeSettings for Chef.Bootstrap.WindowsAzure.LinuxChefClient V 1210.12.102.1000
2016/04/20 23:06:55 Spawned enable.sh PID 1879
2016/04/20 23:07:00 Process 1879 returned non-zero exit code (1)
2016/04/20 23:07:00 Enable failed for Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000
2016/04/20 23:07:00 Processing completed for Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000
2016/04/20 23:07:00 Finished processing ExtensionsConfig.xml

And the custom.log:
/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000
Call for Checking linux distributor
Starting installation process:
23:05:45
Checking for curl...
Detected curl...
Reading chef-client version from settings file
Installing chef-client package
Selecting previously unselected package chef.
(Reading database ... 52410 files and directories currently installed.)
Preparing to unpack /tmp/tmp.CtiseXIt07/chef ...
Unpacking chef (12.9.38-1) ...
Setting up chef (12.9.38-1) ...
Thank you for installing Chef!
[Wed Apr 20 23:06:48 UTC 2016] Package Chef installed successfully.
End of installation:
23:06:48
[Wed Apr 20 23:06:49 UTC 2016] Installing Azure Chef Extension gem
Successfully installed azure-chef-extension-0.0.1
1 gem installed
[Wed Apr 20 23:06:51 UTC 2016] Azure Chef Extension gem installation succeeded

Deployment output:
New-AzureRmResourceGroupDeployment : 16:23:02 - Resource Microsoft.Compute/virtualMachines/extensions 
'akcheflin6/LinuxChefExtension' failed with message 'The resource operation completed with terminal provisioning state 'Failed'.'
At C:********\linux_vm_deploy_script_LOCAL.ps1:54 char:1
- New-AzureRmResourceGroupDeployment -Name $deployName -ResourceGroupNa ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

New-AzureRmResourceGroupDeployment : 16:23:02 - VM has reported a failure when processing extension 'LinuxChefExtension'. Error 
message: "chef-service enable failed - ["Error enabling chef-client service - No such file or directory @ rb_sysopen - 
/etc/chef/client.rb - Check log file for details", "error"]".
At C:********\linux_vm_deploy_script_LOCAL.ps1:54 char:1
- New-AzureRmResourceGroupDeployment -Name $deployName -ResourceGroupNa ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

It's like the extension fails silently, and then continues installing Chef without doing anything with my parameters I pass it. Help!

**Comment by dheerajd-msys** [comment]
@Rev68 ,
Could you please provide your deployment template and parameter file if used?
I have compared your log file `CommandExecution.log` details with mine where I was able to successfully deployed a single VM. I noticed there could be a problem while downloading the extension and enable.sh might be corrupted.

**Comment by Vasu1105** [comment]
Closing this issue due to age.
