### ISSUE TITLE
Can I use my own client.rb if I apply the extension via ARM?

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#138]
According to the readme, it looks like I can upload the contents of my own client.rb if I apply the extension using PowerShell but I don't see a way to do this via ARM. Is this possible?

**Comment by NimishaS** [comment]
@aarsan , if you are using ARM template, then you can specify the `client.rb` options in `settings` field here: https://github.com/Azure/azure-quickstart-templates/blob/master/chef-json-parameters-linux-vm/azuredeploy.json#L260-L268.

**Comment by aarsan** [comment]
I am using a very customized client.rb file which the arm template does not provide options for, unfortunately. It would be great if I could just pass my client.rb in.

**Comment by rubeon** [comment]
You can add stuff to the client.rb with with the `client_rb` field in `settings` in the template.

For example, here's the resource in my template:

```json
      "type": "Microsoft.Compute/virtualMachines/extensions", 
      "properties": {
        "protectedSettings": {
          "validation_key": "[parameters('chefValidationKey')]"
        }, 
        "publisher": "Chef.Bootstrap.WindowsAzure", 
        "typeHandlerVersion": "1210.12", 
        "type": "LinuxChefClient", 
        "settings": {
          "bootstrap_options": {
            "environment": "[parameters('environmentName')]", 
            "secret": "[parameters('chefSecret')]", 
            "validation_client_name": "[parameters('chefValidationName')]", 
            "chef_node_name": "[parameters('webServers')[copyIndex()][1]]", 
            "chef_server_url": "[parameters('chefUrl')]"
          }, 
          "runlist": "[parameters('webServers')[copyIndex()][3]]", 
          "client_rb": "[parameters('chefClientRbOptions')]"
        }
      }, 
```

And here's what I put into my parameters file:

```json
    "chefClientRbOptions": {
      "value": "http_proxy 'http://10.1.1.10:3128'\nhttps_proxy 'http://10.1.1.10:3128'\nssl_verify_mode :verify_none\n"
    }, 

```
The resulting config.rb inserts the value of client_rb in the top of the file.

**Comment by aarsan** [comment]
oh, cool. Am I limited to certain options? Or, does whatever I put in 'chefClientRbOptions' show up in my client.rb?

**Comment by rubeon** [comment]
It's worked for me so far; doesn't seem to very well-document, but it looks like it just prepends whatever you have in there to your file.  I assume you could even have it run some custom Ruby code, if you like ;)

Unfortunately, it does seem to drop a Windows crlf (^M) at the end, so make sure put a \n at the end of your `json`-escaped string value.

**Comment by aarsan** [comment]
Yep, I need some custom ruby in there. Thanks, I'll give this a shot!

**Comment by aarsan** [comment]
this works :)
