### ISSUE TITLE
Passing secret for decrypting data bags is not working

### ISSUE THREAD

**Issue by dreznicek** [chef-partners/azure-chef-extension#152]
Hey Team!

I have been trying to use the `secret` bootstrap option with no success. I have tried to put the secret key in the template file itself as a string or passing it on the command line, but no luck. What I noticed is that the  actual secret file itself is `UTF-8` but when I look at the file that gets created by the azure-chef-extension, it appears to be `ANSI` encoded. This is happening whether I try to bootstrap a Linux or Windows VM.

I could certainly be doing something wrong, but the doc isn't too detailed on how I need to pass the string.

Thanks so much for the extension!

**Comment by dreznicek** [comment]
Anybody else having this problem? I'm really at an impasse with our workflow.

**Comment by NimishaS** [comment]
@dreznicek , sorry for the delayed response. We are going to look into this.

**Comment by NimishaS** [comment]
@dreznicek, I wasn't able to reproduce this issue. I followed the following steps:
1. Create an encrypted databag secret
2. Create a recipe which is reading the contents of the encrypted databag and copying them in a file
3. Pass the `encrypted_data_bag_secret` contents in `bootstrap_options` in the template file
```
{
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(variables('vmName'),'/', variables('vmExtensionName'))]",
            "apiVersion": "2015-05-01-preview",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[concat('Microsoft.Compute/virtualMachines/', variables('vmName'))]"
            ],
            "properties": {
                "publisher": "Chef.Bootstrap.WindowsAzure",
                "type": "LinuxChefClient",
                "typeHandlerVersion": "1210.12",
                "settings": {
                  "bootstrap_options":
                  {
                    "chef_node_name" : "[parameters('chef_node_name')]",
                    "chef_server_url" : "[parameters('chef_server_url')]",
                    "validation_client_name" : "[parameters('validation_client_name')]",
                    "encrypted_data_bag_secret" : "[parameters('secret')]"
                  },
                    "runlist": "[parameters('runlist')]"
                },
                "protectedSettings": {
                    "validation_key": "[parameters('validation_key')]"
                }
            }
        }
```
**Note**: `encrypted_data_bag_secret` contents need to be passed and not the path.
4. Pass the recipe created in step#2 in the `runlist` in template file

Please let us know if you used the template in the same way. Also, for which platform did u face this issue? Currently I tried for linux.

**Comment by dreznicek** [comment]
Thanks for testing this @NimishaS . I think I am doing the same thing and happens both on windows and linux. I am passing the secret in to the template as:

    -secret 'inDK4ZY...lots of stuff...NSpkwqRVc='

If I scp the secret file itself onto the linux box or copy the secret file onto the windows box it works every time.

Am I not passing it correctly on the command line?

**Comment by dreznicek** [comment]
@NimishaS what you are doing is not actually decrypting a data bag with the secret, you are just reading the contents of the key itself and writing those to a file, right? If you try to actually doing something like...

    rabbitmq_user = node['cookbook-rabbitmq']['rabbitmq_user']
    secret = Chef::EncryptedDataBagItem.load_secret(Chef::Config[:encrypted_data_bag_secret])
    accounts_data_bag_item = Chef::EncryptedDataBagItem.load('accounts', node.chef_environment, secret)
    rabbitmq_user_password = accounts_data_bag_item["#{rabbitmq_user}"]

the chef run will blow up with

    Chef::EncryptedDataBagItem::DecryptionFailure
    ---------------------------------------------
    Error decrypting data bag value: 'bad decrypt'. Most likely the provided key is incorrect.

on the last line when it tries to set the `rabbitmq_user_password` variable.

**Comment by dreznicek** [comment]
@NimishaS OK, I figured out how to make it work.

If I use the following command to generate my secret on a `windows` box...

    openssl rand -base64 512 | tr -d '\r\n' > secret_key

Then it creates a file that does not work. If I run that same command on a `linux` box and use THAT file instead, it works. So however the file is being written on the node doesn't like the carriage return of the windows generated secret methinks.

**Comment by NimishaS** [comment]
Ah yes @dreznicek. I also generated the secret key on `linux` box which works.

Please close this issue if it's resolved.
