### ISSUE TITLE
Can't bootstrap nodes with on-prem Chef server

### ISSUE THREAD

**Issue by JonGriggs** [chef-partners/azure-chef-extension#156]
Hi there, 

I've successfully used this extension to bootstrap Windows nodes via ARM template when using Hosted Chef, however with my own on-prem chef server, I am getting the following errors on clients when deploying the same way as I did with Hosted Chef:

`C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000>set path=C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\; 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000>ruby C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.105.1000\bin\chef-enable.rb 
2016-07-27 15:05:25 +0000 extension_root --> C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.105.1000
2016-07-27 15:05:25 +0000 Creating EnableChef object with []...
2016-07-27 15:05:25 +0000 Running Chef extension enable command...
Bootstrap directory [C:/chef] already exists, skipping creation...
2016-07-27 15:05:25 +0000 Creating chef configuration files
[2016-07-27T15:05:26+00:00] ERROR: Chef client key parsing error. #<OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: header too long>
[2016-07-27T15:05:26+00:00] ERROR: Chef Server SSL certificate parsing error. #<OpenSSL::X509::CertificateError: header too long>
2016-07-27 15:05:26 +0000 Created chef configuration files
2016-07-27 15:05:26 +0000 Launching chef-client to register node with the runlist
2016-07-27 15:05:26 +0000 Successfully launched chef-client process with PID [1052]
2016-07-27 15:05:26 +0000 Getting chef-client service status
2016-07-27 15:05:26 +0000 Installing chef-client service...
2016-07-27 15:05:32 +0000 Installed chef-client service.
Logging status message: chef-service installed
2016-07-27 15:05:32 +0000 Starting chef-client service...
2016-07-27 15:05:37 +0000 Started chef-client service.
Logging status message: chef-service enabled`

Further, this is my chef-stacktrace.out file:

`OpenSSL::SSL::SSLError: SSL Error connecting to https://onpremchefserver/organizations/cheforg/clients - SSL_connect returned=1 errno=0 state=error: certificate verify failed
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/http.rb:376:in `rescue in retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/http.rb:333:in `retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/http.rb:299:in `send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/http.rb:144:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/http.rb:127:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/api_client/registration.rb:96:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/api_client/registration.rb:87:in `create_or_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/api_client/registration.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/client.rb:620:in `register'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:268:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:244:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:227:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:442:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:442:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:426:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:63:in `load'
C:/opscode/chef/bin/chef-client:63:in `<main>'`

I am able to successfully bootstrap a Windows server from my Chef workstation with no issue, and I've made sure the validation.pem key that gets placed in c:\chef is identical on successfully bootstrapped clients and unsuccessfully bootstrapped clients.  

Looking forward to some help!
Jon

**Comment by JonGriggs** [comment]
Relevant ARM template info:  

`        {
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(parameters('vmName'),'/', 'chefExtension')]",
            "apiVersion": "2015-05-01-preview",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]"
            ],
            "properties": {
                "publisher": "Chef.Bootstrap.WindowsAzure",
                "type": "ChefClient",
                "typeHandlerVersion": "1210.12",
                "settings": {
                    "bootstrap_options": {
                        "chef_node_name": "[parameters('vmName')]",
                        "chef_server_url": "https://bos1chef01.aspect.com/organizations/aspectops",
                        "validation_client_name": "aspectops-validator"
                    },
                    "client_rb": "ssl_verify_mode \"verify_none\"",
                    "runlist": "recipe[wincfg::baseos_conf]"
                },
                "protectedSettings": {
                    "validation_key": "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCA. . . . fZIF1z4SKn54B\n-----END RSA PRIVATE KEY-----"
                }

            }
        }`

**Comment by stuartpreston** [comment]
@JonGriggs Have you tried adding (under settings?)

```
"client_rb": "ssl_verify_mode :verify_none"
```

**Comment by JonGriggs** [comment]
Thanks @stuartpreston that worked for me.  Is this because the server is using it's self-signed SSL cert?  I was thinking since the org-validator.pem key matched up with the org certificate, the self-signed cert wouldn't matter for client registration.  

In case you haven't noticed, I'm a Chef newbie.  Thanks again, and I'm enjoying your book.

**Comment by stuartpreston** [comment]
@JonGriggs Yes, it's because you have a self-signed SSL cert.  The SSL verification is just to support the transport layer from the client to your server. The org-validator key is sent separately once the connection has been established (it's not part of the SSL negotiation).

Glad to hear you are enjoying the book!
