### ISSUE TITLE
How do i get the newest version on Windows VMs?

### ISSUE THREAD

**Issue by chlsmith** [chef-partners/azure-chef-extension#162]
No matter what I try, I end up with version 12.3 of the Chef client when I deploy with an ARM template.   The quickstarts from MS have a VM with Chef client installed, but the "autoupdate" value is never used in the template, so I don't know where to put it.   Also, I have no idea where to tell it the version of the client to use...is it "typeHandlerVersion"?

Here's what I have used and it's yet to really work the way I'd expect.   Nothing I see lets me pick the most recent version of the client, nor is there anything in there to update automatically.

       {
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(parameters('vmNameBase'),copyIndex(1),'/ChefClient')]",
            "apiVersion": "2015-06-15",
            "location": "[variables('location')]",
            "copy": {
                "name": "vmCopy",
                "count": "[parameters('vmCount')]"
            },
            "dependsOn": [
                "[concat('Microsoft.Compute/virtualMachines/', parameters('vmNameBase'),copyIndex(1))]"
            ],
            "properties": {
                "publisher": "Chef.Bootstrap.WindowsAzure",
                "type": "ChefClient",
                "typeHandlerVersion": "1207.12",
                "settings": {
                    "bootstrap_options": {
                        "chef_node_name": "[concat(parameters('vmNameBase'),copyIndex(1))]",
                        "chef_server_url": "[parameters('chef_server_url')]",
                        "validation_client_name": "[parameters('validation_client_name')]"
                    },
                    "runlist": "[parameters('runlist')]"
                },
                "protectedSettings": {
                    "validation_key": "[parameters('validation_key')]"
                }
            }
        }

**Comment by stuartpreston** [comment]
Hi @chlsmith - you should update typeHandlerVersion to the value of the latest extension ```1210.12```.  Around the time of 1207.12 a change was made so that every version of the extension installs the latest version of the Chef Client.

You can use the following PowerShell to retrieve the list of Extension versions:

```powershell
Get-AzureRmVMExtensionImage -Location "West Europe" -PublisherName "Chef.Bootstrap.WindowsAzure" -Type "ChefClient" | ft
```

**Comment by NimishaS** [comment]
@chlsmith , Please go with the solution provided by @stuartpreston to get the latest version of `chef-client`. Let us know if your issue is resolved.

**Comment by NimishaS** [comment]
Closing this issue. @chlsmith please let us know if the issue still persists
