### ISSUE TITLE
While provisioning with MS Chef extension noticed that var/log/azure/Chef.Bootstrap.WindowsAzure.LinuxChefClient/1210.12.105.1001/chef-client.log  is empty

### ISSUE THREAD

**Issue by tsp0001** [chef-partners/azure-chef-extension#163]
While provisioning with MS Chef extension noticed that var/log/azure/Chef.Bootstrap.WindowsAzure.LinuxChefClient/1210.12.105.1001/chef-client.log  is almost empty:

# cat /var/log/azure/Chef.Bootstrap.WindowsAzure.LinuxChefClient/1210.12.105.1001/chef-client.log
# Logfile created on 2016-08-12 21:51:59 -0500 by logger.rb/53938

Any idea why?

**Comment by dheerajd-msys** [comment]
@tsp0001,

On my spawned vm with chef extension version 1210.12.105.1001, the chef-client.log file is showing the logs properly.
Can you share additional details Linux OS type, image name, logs at following locations

**Comment by tsp0001** [comment]
Issue is resolved, thank you


Be Well,
    Sergey

Sergey Prilutsky
   EIS-X86 Engineering
    Walgreens/Corp/ESS/EIS
   Office: 224-542-6196
   e-mail: sergey.prilutsky@walgreens.com<mailto:sergey.prilutsky@walgreens.com>


[Description: Walgreens purpose_disclaimer]
