### ISSUE TITLE
Custom json attributes in first-boot.json?

### ISSUE THREAD

**Issue by matkam** [chef-partners/azure-chef-extension#164]
Is there a way to add custom node attributes, passed in as a json string, when bootstrapping a node? Knife bootstrap supports a "--json-attributes" flag to do this, and sets them in the first-boot.json file.

**Comment by NimishaS** [comment]
@matkam , you can use `--bootstrap-options` option for setting node attributes. It accepts json input. Following attributes can be set: `environment`, `chef_node_name`, `chef_server_url`, `validation_client_name`, `secret`, `node_verify_api_cert` and `node_ssl_verify_mode`

**Comment by matkam** [comment]
@NimishaS those are options used in bootstrapping, but what about attributes that get saved on the chef server for the node (https://docs.chef.io/attributes.html)? My use case here is wanting to be able to set attributes on a node to be used in a recipe, without having to create and assign a role.

**Comment by Vasu1105** [comment]
@matkam you can use "custom_json_attr" attribute in template inside chef extensions settings or you can use "--json-attributes" option in knife azure server create to set your attributes and use bootstrap protocol cloud api for bootstraping.

**Comment by dreznicek** [comment]
@Vasu1105 I tried setting the following in my ARM template and it did not work:

```
"properties": {
  "settings": {
    "custom_json_attr": {
      "cookbook-rabbitmq": {
        "cluster_count": "[parameters('numberOfInstances')]"
      }
    }
  }
}
```
where `[parameters('numberOfInstances')]` is set to `2`, for example, and that does not set the attribute on the node after its been bootstrapped. Are you sure that feature is available, or am I doing it wrong?

**Comment by Vasu1105** [comment]
@dreznicek  I will verify this

**Comment by Vasu1105** [comment]
@dreznicek  it looks to be issue in extension will be fixing this. Thanks @matkam & @dreznicek

**Comment by dreznicek** [comment]
Awesome to here @Vasu1105! This will actually increase the quality of my life quite a bit, so let me know how I can help :)

**Comment by matkam** [comment]
Any chance you can add the custom_json_attributes as a command line option, maybe even part of --bootstrap-options?

**Comment by Vasu1105** [comment]
@matkam we will be working on adding a attribute in template for xplat and azure-powershell,  This will be a part of public settings in template. Through knife azure user will able to set this using --json-attribute option. We are making necessary changes in extension first and then will work in adding this in xplat and azure-powershell.

**Comment by Vasu1105** [comment]
@matkam  & @dreznicek we released new version of azure-chef-extension i.e. 1210.12.106.1000 it support for custom json attributes now. Please refer [https://github.com/chef-partners/azure-chef-extension/blob/master/README.md]
