### ISSUE TITLE
Running as Scheduled Task instead of service

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#165]
Chef recommends running the Chef Client as a Scheduled Task in Windows, rather than a Windows service. Are there any plans for this extension to choose between task and service?

**Comment by btm** [comment]
Yes. As of [Chef 12.18](https://discourse.chef.io/t/chef-12-18-31-released/10275) released last week, the Chef client installer MSI supports setting up the client to run as a scheduled task or as a service (or neither).

Similar support is being added to the extension right now in https://github.com/chef-partners/azure-chef-extension/pull/188.

**Comment by NimishaS** [comment]
This feature has been added in the latest `azure-chef-extension 1210.12.108.1000`. Please check the usage of `daemon` option for details: https://github.com/chef-partners/azure-chef-extension#options-that-can-be-set-in-publicconfigconfig
