### ISSUE TITLE
Syntax clarification: runlists

### ISSUE THREAD

**Issue by glennmate** [chef-partners/azure-chef-extension#166]
Can there be a syntax clarification on the format of the string to pass for the runlist parameter? I have a bit of confusion .

```
    "runlist": {
      "value": "recipe[chef-client],recipe[organization-role::default]"
    },
```
versus
```
    "runlist": {
      "value": "recipes[chef-client,organization-role::default,organization-role2::special]"
    },
```
I'm deploying ARM templates via AzureCLI, for context. Silly question as I'm fairly certain it's the former (don't have time to test this quite yet).

**Comment by NimishaS** [comment]
@glennmate , yes the first syntax is correct.
Please confirm if your issue is resolved.

**Comment by glennmate** [comment]
I'm having a lot of timeouts with the Azure chef extension across known working / good Azure Resource Manager templates the past few days so I'll test once it's stable again. Thanks for verifying @NimishaS

**Comment by NimishaS** [comment]
@glennmate , we tried a few times and didn't face the timeout issue with the extension. Please open a new issue in case your issue still persists.
Closing this issue for now.
