### ISSUE TITLE
Secret parameter should be retrieved from Protected Settings

### ISSUE THREAD

**Issue by russellseymour** [chef-partners/azure-chef-extension#168]
When using a `secret` for an encrypted data bag it can be passed as a `securestring` in the parameters, but the extension takes the value from the `bootstrap_options` and not `protectedSettings`.

https://github.com/chef-partners/azure-chef-extension/blob/master/lib/chef/azure/commands/enable.rb#L171

Could this be changed so that it is specified in `protectedSettings` in the ARM template?

**Comment by NimishaS** [comment]
This has been fixed in latest extension `1210.12.106.1000`.
