### ISSUE TITLE
install on windows not respecting proxy config

### ISSUE THREAD

**Issue by cedwards-reisys** [chef-partners/azure-chef-extension#170]
https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.psm1

line: 44

I needs to respect the proxy setup at the system level.

Maybe doing something like this:

```
        $proxyAddr = (get-itemproperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings').ProxyServer
        $proxy = new-object System.Net.WebProxy
        $proxy.Address = $proxyAddr
        $proxy.useDefaultCredentials = $true

        $wc = new-object system.net.WebClient
        $wc.proxy = $proxy

        iex $wc.DownloadString('https://omnitruck.chef.io/install.ps1');install
```

**Comment by NimishaS** [comment]
@cedwards-reisys , there's an option to pass `environment_variables` to the extension. In that you can pass the proxy settings too.
Does that resolve your issue?

**Comment by dheerajd-msys** [comment]
@cedwards-reisys Did you get a chance to try out with `environment_variables` as mentioned in above comment. Please check and let us know your feedback. If that resolve your issue, please close the ticket.

Thanks

**Comment by Vasu1105** [comment]
Closing this issue due to age.
