### ISSUE TITLE
Support Windows Nano Server

### ISSUE THREAD

**Issue by mwrock** [chef-partners/azure-chef-extension#171]
It would be great to use the azure extension to install chef on azure deployed chef Nano Server VMs. Due to the stripped down nature of Nano Server, there are some changes that would need to be made in this repo to accomodate Nano.
1. Any powershell used must comply with the APIs supported by the .Net core runtime (as opposed to the Full .Net API). If you look at the PR at https://github.com/chef/knife-windows/pull/399 which adds nano support to `knife bootstrap` in knife-windows. It leverages the [mixlib-install](https://github.com/chef/mixlib-install) gem for all of the chef-client download and install scripts. You may not be able to use that gem directly here because you need a ruby runtime but you could use that gem as a reference creating the scripts.
2. You need an appx package to install chef on Nano. In `knife bootstrap` one currently has to pass a custom URL to `--msi-url` that points to a chef-client appx. An url that currently works is https://s3-us-west-2.amazonaws.com/nano-chef-client/chef-12.14.60.appx I'm not familiar enough with the extension to know if that is possible - to pass a custom url. If not we may need to wait for appx packages to be delivered from Omnitruck.

**Comment by stuartpreston** [comment]
Closing this issue due to age.  The direction for Nano Server has changed, we will revisit later if we produce Nano Server specific builds in the future.
