### ISSUE TITLE
Make installation of the Chef Windows service optional

### ISSUE THREAD

**Issue by russellseymour** [chef-partners/azure-chef-extension#174]
The recommendation is to now run the `chef-client` as a scheduled task rather than as a Windows Service.

Why Run Chef with the Task Scheduler vs. the Windows Service?
- More scheduling options - task scheduler can run configurable cycles (think maintenance windows)
- Can run on demand
- Does not lock the log file between chef runs (for log rotation)
- Better visibility into when Chef is actually running on the box and what the last exit code was.
- The chef service is buggy - in a way that is really hard to reproduce and therefore fix.

The Chef service is just a less resilient, less transparent version of task scheduler.  In order to be sure that chef is running, you'll have to watch either log files or check-ins to the server.  The task scheduler gives us better options and is the Microsoft recommended way to run a command that needs to run on a schedule or in response to certain conditions.  If you don't have something that has to run all the time in the background or listen for incoming connections, you should not be a service.

The extension should have a new option for installing the optional service from the MSI, which will be false by default, something like `install_service: true|false`.  This is a breaking change and the new option is to support people that still rely on the service but it has to be explicitly enabled.  However eventually this option will be removed as well.

The `chef-client` cookbook does not support the windows service any more just the scheduled task.  It is recommended that people include the cookbook in there initial run using the extension so that they end up with a system that is being managed by Chef.

This would also address the issue raised by @aarsan in issue #165.

/cc @smurawski

**Comment by aarsan** [comment]
The first phase of this rollout could be to have install_service default to true. this would prevent this change from being breaking, but also allow whoever needs/wants this to take advantage of it.

**Comment by btm** [comment]
We need to implement the scheduled task at a higher level, e.g. in the MSI, so we should

1) do this install_service bit
2) do the scheduled task in the msi
3) add a install_task feature

**Comment by russellseymour** [comment]
@btm I had a chat with @smurawski about this at the London Summit and we thought that it would not have to be something that the MSI would do as that requires a change to the product.

The approach we thought for this was to state that the `chef-client` cookbook would be on the Chef Server and the runlist would include the `task` recipe.  That way there is no duplication of code.

Admittedly it does add a dependency on a cookbook that we have not had before but it does mean that we do not need to change the existing installation process for `chef-client` on Windows.  We would just be changing the optional service component.

**Comment by btm** [comment]
@russellseymour, everyone in the Chef Windows community has been talking about wanting to promote the use of the scheduled task over a service for a while now; consensus is that it's the way forward but we have been poor at communicating that.

The work of modifying the MSI to create a schedule task is pretty straightforward; there's nothing preventing us from just doing it besides just finding someone to do it. Making the change in the MSI puts the pattern right in front of the user and makes it very accessible.

On the other hand, modifying the process on Azure to use the chef-client cookbook only improves our situation there and creates a "one-off."

I've already put the work of the scheduled task in the msi on our contractors board, we should have it in a couple weeks.

**Comment by btm** [comment]
Referring to my list above in https://github.com/chef-partners/azure-chef-extension/issues/174#issuecomment-258159130

1. It's possible to set the service interval to 0 and then the service won't be installed. This was done in https://github.com/chef-partners/azure-chef-extension/pull/161 and released in 1210.12.106.1000 and later.

2. As of [Chef 12.18](https://discourse.chef.io/t/chef-12-18-31-released/10275) released last week, the Chef client installer MSI supports setting up the client to run as a scheduled task or as a service (or neither).

3. Similar support for a scheduled task is being added to the Azure Chef extension right now in https://github.com/chef-partners/azure-chef-extension/pull/188.

**Comment by NimishaS** [comment]
This feature has been added in the latest `azure-chef-extension 1210.12.108.1000`. Please check the usage of `daemon` option for details: https://github.com/chef-partners/azure-chef-extension#options-that-can-be-set-in-publicconfigconfig
