### ISSUE TITLE
interval 1800

### ISSUE THREAD

**Issue by chlsmith** [chef-partners/azure-chef-extension#177]
Putting "interval 1800" in the client.rb by default causes it to take 30min to start up chef-client.   I tried to run it manually from a prompt, and it just sits there.   the chef-client.log file gets created immediately, but then the prompt just sits and does say "starting Chef client...."

I'm running chef-client as a scheduled task.....commenting out this line fixed my problem.  Is this something that you should be doing by default?

**Comment by NimishaS** [comment]
@chlsmith , is it like you have both `chef service` and `scheduled task` installed on your machine?
At present the extension supports only the chef service and hence client.rb has `interval 1800` by default, which is expected.

**Comment by Roudaille77** [comment]
If you want to run the client manually and bypass the interval parameter, you can just add the `--once` argument when running `chef-client`.

**Comment by krishus** [comment]
@NimishaS 
I don't want to use "interval 1800" in the client.rb by default. Is there a way to remove "interval 1800" from my client.rb file?? by using extension script??. Please let me know.

**Comment by NimishaS** [comment]
@krishus , the latest version of extension supports both `chef service` and `scheduled task`. For that there an option `daemon` which accepts `none/service/task`. If you want to change the interval of `chef service` or `schedules task`, you can use `chef_daemon_interval` option.

Please refer https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage.
