### ISSUE TITLE
Extension doesn't unblundle intermediate and root certs

### ISSUE THREAD

**Issue by SiloReed** [chef-partners/azure-chef-extension#194]
The 'chef_server_crt' parameter doesn't handle a Base64 .pem certificate bundle properly. It appears to only unpack the first certificate in the bundle and saves it to "C:\chef\trusted_certs\chefserver_cert.crt". The intermediate and root certificates in the bundle are not saved as separate files in "C:\chef\trusted_certs\". I am using the same .pem file is saved as /var/opt/opscode/nginx/ca/<fqdn>.crt on the Chef server. 

I'm trying to use a certificate issued by an internal Windows subordinate CA. The "C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.108.1000\chef-client.log" records this event:
SSL Validation failure connecting to host

Note that executing 'knife ssl fetch' manually on a Chef workstation downloads all three certs and saves them to C:\chef\trusted_certs\

**Comment by dheerajd-msys** [comment]
@SiloReed, I reached to the following conclusion after analysis: 
a) When we pass intermediate certificate followed by root certificate to `chef_server_crt` parameter then we will get only one certificate with name `chefserver_cert.cert` on location `C:\chef\trusted_certs`.
b) If we open this certificate with `crypto shell extensions`, we can see root certificate followed by intermidate certificate from the tab `certificate path`. If you want you can copy root certificate, then "copy to file" option is present in "Details" tab. 
c) But if we pass certificate vice-versa then we will able to see only root certificate & not an intermediate one.                   

Can you please confirm if you are passing the certificate in the correct order. i.e. intermediate certificate followed by root certificate? If yes, then please try opening the certificate with `crypto shell extensions`.

**Comment by NimishaS** [comment]
@SiloReed , any updates here?

**Comment by SiloReed** [comment]
When I open the PEM .crt file containing all three certs, the Crypto Shell Extension displays the UI for the server cert. The certificate path shows the correct chain from the Root CA down to the intermediate down to the server.  The correct order for this bundle on the Chef side is server, intermediate, root. @dheerajd-msys appears to have reproduced my problem: Only one certificate is extracted, that is the first one in the bundle. All other certificates are ignored. All certificates need to be extracted from the bundle and saved in C:\chef\trusted_certs\. 

I've since worked around the problem by using the Azure Custom Script extension to create the C:\chef\trusted_certs\ and copy the three certificates to that directory. Then the Chef extension runs and it's happy because all 3 certs exist.

Does the Chef extension accept the certificate bundle in PKCS#7 format as opposed to PEM?

**Comment by dheerajd-msys** [comment]
@SiloReed, Could you please help me with names of your generated 3 certs that you have generated through Azure Custom Script extension. I mean if certs have any specific name or random ones.

**Comment by SiloReed** [comment]
The three certificate files downloaded by the Custom Script are stored in a Azure storage account blob:
ze1pxchef01_citrite_net.crt  (The server certificate)
ftlissuingca01.crt  (The internal intermediate CA)
ROOTCA.crt (The offline internal root CA)

I've since worked around the problem by using a wild-card certificate that was issued by a public CA. Then I use the wildcard certificate in the Chef extension. Since the public CA is in the list of trusted CAs on the Chef DK, the wildcard certificate is considered valid. 

With that said, I still think the Azure Chef Extension should accept a certificate bundle (*.p7b) file that contains 3 certs, the server cert, intermediate cert, and root cert, that way it could work with a Chef server that was using a certificate issued by an internal CA.

**Comment by NimishaS** [comment]
@SiloReed , splitting of certificate has been fixed by @dheerajd-msys in https://github.com/chef-partners/azure-chef-extension/issues/209.

The extension currently doesn't support `certificate bundle (*.p7b) file`. Since this will be a new feature, there should be a different issue for this.

**Comment by NimishaS** [comment]
This issue should be resolved in version 1210.12.109.1004 of the extension.

Created https://github.com/chef-partners/azure-chef-extension/issues/214 for supporting `certificate bundle (*.p7b) file`.
