### ISSUE TITLE
Runlist conflicts with policy_name and policy_group settings in first-boot.json

### ISSUE THREAD

**Issue by jkerry** [chef-partners/azure-chef-extension#211]
When a runlist isn't specified and policy_name and policy_group settings are added to the  custom json attributes like so:
```
"custom_json_attr": {
            "policy_group": "[parameters('chefPolicyGroup')]",
            "policy_name": "[parameters('chefPolicyName')]"
          }
```

an empty run list is still added to the first-boot.json file.  These settings conflict causing the first converge to fail. The resolution would be to not write a run_list into the first-boot.json file at all if the runlist is not provided.

This, for a linux host, appears to happen here:
https://github.com/chef-partners/azure-chef-extension/blob/bccc0cff872413b2818d942aec5d15d7325e5256/lib/chef/azure/commands/enable.rb#L220

**Comment by btm** [comment]
This should be fixed by #213 in version 1210.12.109.1004 of the extension.
