### ISSUE TITLE
How can we set client.pem in chef-extension using ARM Template.

### ISSUE THREAD

**Issue by krishus** [chef-partners/azure-chef-extension#222]
I already created a node from my workstation using knife. How can we set client.pem through ARM Template.

**Comment by NimishaS** [comment]
@krishus , usually ARM template is used for creation of VM + installation of extension: https://github.com/Azure/azure-quickstart-templates/tree/master/chef-json-parameters-linux-vm

In your case, it seems like you have already created a VM and would like to bootstrap that using `azure-chef-extension`. For that purpose you can use `knife-azure` gem. Please refer this command: https://github.com/chef/knife-azure/blob/master/docs/bootstrap.md#arm-mode

**Comment by krishus** [comment]
@NimishaS , No I'm not talking about existing VM's. I know we use ARM template to creation of VM + installation of extension, in this extension we can specify the validationKey, client.rb options in settings field in the ARM template and Value of parameters like chef_server_url, validation_client_name etc can be passed in the template parameters file. So here my question is can we have any option to add client.pem??

**Comment by NimishaS** [comment]
@krishus , If you are passing the extension in the ARM template as mentioned [here](https://github.com/Azure/azure-quickstart-templates/blob/master/chef-json-parameters-linux-vm/azuredeploy.json#L265-L293), the extension will bootstrap the node and `client.pem` file will automatically get created.
We don't need to pass `client.pem` file manually through the ARM template.

**Comment by NimishaS** [comment]
@krishus , any update on this?
