### ISSUE TITLE
Error when upgrade to 1210.12.109.1005

### ISSUE THREAD

**Issue by amarkulis** [chef-partners/azure-chef-extension#226]
We ran into the errors below after restarting a machine.  The extension got stuck in transitioning.

[CommandExecution.TXT](https://github.com/chef-partners/azure-chef-extension/files/1246549/CommandExecution.TXT)
[CommandExecution_0.TXT](https://github.com/chef-partners/azure-chef-extension/files/1246550/CommandExecution_0.TXT)

**Comment by NimishaS** [comment]
@amarkulis , in this case did your VM previously had `1210.12.109.1004` extension installed and auto upgraded to `1210.12.109.1005` when it was released? OR was `update.cmd` run manually for some reason?

**Comment by amarkulis** [comment]
It looks like it auto updated I think this is directly related tp https://github.com/chef-partners/azure-chef-extension/issues/225

**Comment by NimishaS** [comment]
@amarkulis , I tested the update scenario by publishing an extension internally and the extension got updated successfully. Please check my logs attached. 
[nim_CommandExecution_0.txt](https://github.com/chef-partners/azure-chef-extension/files/1266252/nim_CommandExecution_0.txt)

I checked your logs and found that `update` process times out after 15 minutes. However in my case it took around 10 seconds only. I checked the point where update process gets stuck from the logs shared by you, but no expensive operation is taking place at that moment.
It seems to me that the system is very slow. Are you observing these failures on `Standard_A2` images?

**Comment by amarkulis** [comment]
@NimishaS The standard_A2 images are not related in this case this is happening in our production tier environment which has higher specs.

**Comment by NimishaS** [comment]
@amarkulis , please share your complete ARM template.
It looks like there's something that is running in parallel when extension update runs. Do you have any scheduled task configured that runs on system start? Or any other task that may be locking the resources required by extension update process?

**Comment by amarkulis** [comment]
@NimishaS Our Arm Template is 5000 lines and I am not comfortable posting it on here. This is happening on provision and upgrade and seems to have only started in the latest version of the extension.

**Comment by NimishaS** [comment]
@amarkulis , I need some way to reproduce the issue. For me the extension is upgrading successfully to the latest one. If possible then please hide the confidential details from the ARM template and then share it.

**Comment by NimishaS** [comment]
@amarkulis , I would like to figure out if any other processes were running at the time of extension update. Please share the Application Event Logs for that. 
Is you machine joined to a domain or standalone? If on a domain, is the act of rebooting also applying approved patches from somewhere?
Please confirm the Windows OS version too.

**Comment by NimishaS** [comment]
@amarkulis , any updates on this?

**Comment by amarkulis** [comment]
This is still an issue.  Here is another error messages.

[CommandExecution.txt](https://github.com/chef-partners/azure-chef-extension/files/1304385/CommandExecution.txt)

**Comment by amarkulis** [comment]
We had it effect 6 nodes today Here are the other two error messages.
[CommandExecution-elastic.txt](https://github.com/chef-partners/azure-chef-extension/files/1304448/CommandExecution-elastic.txt)
[CommandExecutionAGENT.txt](https://github.com/chef-partners/azure-chef-extension/files/1304449/CommandExecutionAGENT.txt)

**Comment by NimishaS** [comment]
@amarkulis , looking at the last 2 logs shared by you in https://github.com/chef-partners/azure-chef-extension/issues/226#issuecomment-329598273, I observed this pattern of error:
```
Copy-Item : The process cannot access the file 'C:\chef\cache\remote_file\https
___kcdevops_blob_core_windows_net_certs_wsus_WSUS_PDTEST101-80ce9e9af7d59ce472f
ee5e3c647cc12.json' because it is being used by another process.
At C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
bin\chef-update.psm1:78 char:5
+     Copy-Item "$backupLocation*" "$bootstrapDirectory\\" -recurse -fo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (https___kcdevop...e3c647cc12.json:F 
   ileInfo) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyDirectoryInfoItemIOError,Microsoft.PowerShel 
   l.Commands.CopyItemCommand
```
During Update, waagent uninstalls the old extension so we keep a backup of `C:\chef` directory. The logs shared by you show error at that moment only as `C:\chef\cache\remote_file\https
___kcdevops_blob_core_windows_net_certs_wsus_WSUS_PDTEST101-80ce9e9af7d59ce472f
ee5e3c647cc12.json` is being used by another process. Can you please check which process is trying to access this file in your case? In the log files shared above, there are other json files too which are being used by some other process.

**Comment by amarkulis** [comment]
Chef is calling powershell for that.

**Comment by amarkulis** [comment]
As I mentioned before all nodes are fixed very quickly by running 

CD C:\opscode\chef\embedded\bin
./gem install C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\gems\azure-chef-extension-0.0.1.gem

Can you just build that in to the upgrade process?

**Comment by NimishaS** [comment]
@amarkulis , the update process is already doing that. `Update` calls `Install-ChefClient` defined in `chef-install.psm1`(https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-update.psm1#L82) and `Install-ChefClient` calls `Install-AzureChefExtensionGem` (https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.psm1#L93).
The problem is that `Update` process is getting timed out before it reaches to that point.
We'll try to figure out if some handler can be implemented in case the timeout happens.
