### ISSUE TITLE
Re-register existing node

### ISSUE THREAD

**Issue by kcighon** [chef-partners/azure-chef-extension#243]
Is it possible to re-register a node that already exists in chef? Similar to the chef provisioners parameter in terraform - recreate_client (https://www.terraform.io/docs/provisioners/chef.html#recreate_client-boolean-)

Useful if a server is redeployed.

**Comment by Vasu1105** [comment]
you can run knife bootstrap command with new node name

**Comment by Vasu1105** [comment]
I hope you just had some queries and not and issue with azure-chef-extension. Please reopen the issue with more details if you are coming across any issues in relation to azure-chef-extension here.
