### ISSUE TITLE
Allow configuration to install from Stable or Current release channel

### ISSUE THREAD

**Issue by scolligan** [chef-partners/azure-chef-extension#244]
I'm currently using Chef Client 13.8.11 as it contains some fixes that were causing my Chef runs to silently abort.  However, I'm not able to specify this version in my ARM template as this version is in the Current channel, and the Azure Chef Extension only looks to the Stable channel for downloads.

Had discussion with @stuartpreston about this in the Chef slack channel and he confirmed source does not allow for this currently.

This would be a great feature to add and would allow me to target the specific version I need during provisioning.  Currently I have to use the latest Stable build and then run through an upgrade process post-provisoning.

Thanks,

Sean

**Comment by scolligan** [comment]
One other thought, it might be nice if this potential new feature followed a pattern similar to the new test kitchen configuration syntax:
```
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.8.11
  channel: current
```

**Comment by NAshwini** [comment]
Hi @scolligan, `bootstarp_channel` options are now available in extension version `1210.12.110.1001` in public cloud.

**Comment by scolligan** [comment]
Excellent!  Is the version you referenced available/released?  I checked the releases, and version `1210.12.110.1000` appears to be the latest.

Thanks!

**Comment by NAshwini** [comment]
Hi @scolligan ,
It is the releases one, on which region or account you are trying to check.
Able to check by:
```
PS C:\Windows\system32>  Get-AzureVMAvailableExtension -ExtensionName ChefClient -Publisher Chef.Bootstrap.WindowsAzure -AllVersions | select ExtensionName,Publisher,Version

ExtensionName Publisher                   Version
------------- ---------                   -------
ChefClient    Chef.Bootstrap.WindowsAzure 11.18.6.2
ChefClient    Chef.Bootstrap.WindowsAzure 1207.12.3.0
ChefClient    Chef.Bootstrap.WindowsAzure 1210.12.109.1004
ChefClient    Chef.Bootstrap.WindowsAzure 1210.12.109.1005
ChefClient    Chef.Bootstrap.WindowsAzure 1210.12.110.1000
ChefClient    Chef.Bootstrap.WindowsAzure 1210.12.110.1001
```
let me know if its still not available.
Thanks.

**Comment by scolligan** [comment]
Hi @NAshwini - sorry, I was looking at the github page and didn't see anything about this version:

https://github.com/chef-partners/azure-chef-extension/releases

I will check on Azure.

Thanks!

Sean

**Comment by Vasu1105** [comment]
Closing this since the feature is added in release 1210.12.110.1001
