### ISSUE TITLE
  "recreate_client":"true"

### ISSUE THREAD

**Issue by hakabo** [chef-partners/azure-chef-extension#250]
The chef provisioner available for terraform has the following argument available

**recreate_client** (boolean) - (Optional) If true, first delete any existing Chef Node and Client before registering the new Chef Client.

Can this be made available for the azure-chef-extension, or an equivalent method?  I'm looking for the ability to rebuild a VM and the chef client able to re-register without needing to delete the previous/existing client.

**Comment by stuartpreston** [comment]
Keeping #252 open to supersede this issue.
