### ISSUE TITLE
Providing an alternative MSI locaton for Extension

### ISSUE THREAD

**Issue by hakabo** [chef-partners/azure-chef-extension#251]
Is it possible to use the azure chef extension but have it make use of the chef-client.msi which I have prestaged on the target VM?

We would like to use the Chef Extension as the method for installing/configuring chef-client but we are not able to let the the VM to reach out to the internet to download any resources. I can however, stage the client-msi on the VM and i'd like the extension to use that rather than reach out to chef.io.

Is this possible? If so, can a bit of sample code be provided? We are programatically deploying the extension using ARM templates (well, doing this via Terraform). I can see that install.ps1 supports various parameters, but it looks like not all of these are passed through via the extension.

**Comment by stuartpreston** [comment]
Hi @hakabo it is not possible to separate the configuration and the installation of the Chef Client (which is, as you say, downloaded from our CDN at enable time).  At a point in the future we are hoping to make the Chef Client small enough that it sits inside the extension to avoid us having to reach the internet to pull it down.

I would also make you aware of this post that outlines the outbound connectivity requirements for VM extensions in Azure, worth a read.

One alternative approach would be to use the Custom Script Extension in Azure to execute the Chef Client MSI, and drop a client.rb file with the required settings into c:\chef (assuming Windows).  You can then use the chef-client and chef_client_updater cookbooks in your run list to keep things up to date from that point.

**Comment by stuartpreston** [comment]
Here's the post I referred to: https://blogs.msdn.microsoft.com/mast/2016/04/27/vm-stuck-in-updating-when-nsg-rule-restricts-outbound-internet-connectivity/

**Comment by stuartpreston** [comment]
Closing - workarounds provided.
