### ISSUE TITLE
Chef Extension installation/reporting issues

### ISSUE THREAD

**Issue by nabeelamjad** [chef-partners/azure-chef-extension#253]
We've had some problems recently with the extension, specifically around reporting and subsequent updates/installs

We've installed the chef extension correctly, but gave it an invalid client validator pem key on purpose, the result is that Azure recognizes as the chef-service being provisioned successfully and running. The node itself provides an error that the PEM is invalid, however this information is not piped back to the Azure error handler and thus we have no visibility via the portal or API.

We also run into issues when changing the PEM/runlist on subsequent updates or uninstall/reinstalls whereby the current `/etc/chef` folder remains unchanged. We did notice some changes under `/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient...`, I don't think they had any impact though.

**Comment by Vasu1105** [comment]
@nabeelamjad currently heartbeat reporting mechanism is off for this extension because. We are only reporting the portal whether extension installation is successful. If something fails at the chef-client run side you need to debug that locally.

**Comment by nabeelamjad** [comment]
Thanks for the response@Vasu1105, so even if the very first chef-client run has failed this has to be debugged locally?

Could you also clarify the situation on uninstalling and then reinstalling the extension? I've noticed that the Chef data persists rather than being cleaned up entirely.

**Comment by stuartpreston** [comment]
@nabeelamjad That's indeed by design, otherwise removal of the extension for upgrade to a different version of the extension would need to generate a new client (and associated keys etc.).  Only the configuration folder should be left behind.
