### ISSUE TITLE
Dynamic Node names in Azure Scale Sets (VMSS)

### ISSUE THREAD

**Issue by nabeelamjad** [chef-partners/azure-chef-extension#256]
We've ran into an issue whereby setting up the Chef Client extension requires the use of a `node_name` (via the Azure portal), this works as expected when dealing with regular virtual machines. However, this behavior does not work correctly with Azure Scale Sets.

The Chef extension is set on a Scale Set level (rather than the VM) and is evaluated only once prior to applying to the underlying VMs. This then causes the machines to not register after the first one as their node names are the same.

We were advised by Azure Support to reach out to Chef regarding this issue and whether it is possible to allow for dynamic node names with the option to add a certain affix/prefix for logical naming.

**Comment by stuartpreston** [comment]
@nabeelamjad Sorry for the delayed response.  A node name doesn't require to be provided to the underlying framework, so it could be just a portal restriction that requires the node name to be provided.  Have you tried deploying using an ARM template or via the az extension command?

**Comment by nabeelamjad** [comment]
@stuartpreston that's correct, after speaking to Azure they have mentioned that the API is free of such restrictions (you do not need to provide a node name), however the portal is restricted to requiring one (which apparently is set by Chef). In any case this solves our issue as we intended to use the API but were testing via the portal first.

**Comment by stuartpreston** [comment]
Thanks, we'll close this for now and are discussing with Microsoft how to get the portal UI updated so that providing node name is optional.
