### ISSUE TITLE
Feature Request: Support Policy

### ISSUE THREAD

**Issue by Xorima** [chef-partners/azure-chef-extension#259]
Hi,

Currently the extension supports a run list option, it would be useful to have a policygroup and policyname option as well for those using policy.

**Comment by NAshwini** [comment]
We can pass `policy_name` and `policy_group` in `custom_json_attr` and issue regarding it has been resolved in PR https://github.com/chef-partners/azure-chef-extension/pull/287. Closing issue.

**Comment by Vasu1105** [comment]
We will be releasing this soon and will also be documenting the usage. Thank you @Xorima.

**Comment by danielcbright** [comment]
@Vasu1105 any updates on when this will be GA and documented?

**Comment by Vasu1105** [comment]
@danielcbright Yes in this week it will be out. Will notify the same.

**Comment by NAshwini** [comment]
@danielcbright Thank You.
We have fix the issue and release it with latest extension https://github.com/chef-partners/azure-chef-extension/releases/tag/1210.13.2.3 and updated the docs with PR's https://github.com/chef-partners/azure-chef-extension/pull/288 and https://github.com/chef-partners/azure-chef-extension/pull/289
