### ISSUE TITLE
Feature Request: Add Ability to Specify chef-client download URL

### ISSUE THREAD

**Issue by danielcbright** [chef-partners/azure-chef-extension#265]
It would be great to be able to download the `chef-client` to a more "local" repo to host to help avoid IP blacklisting if many clients download from Chef public servers at once, and also to help make the install process faster for more remote Azure datacenter locations.

**Comment by NAshwini** [comment]
Thank you @danielcbright, for bringing up this feature request. We have come up with above PR for installing downloaded chef-client from local repo. 
  Please note that azure VM Extensions themselves requires access to Azure Storage in that region - see https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-linux#network-access for the requirements. This has been the reason we have not added the complete airgapped functionality.

**Comment by danielcbright** [comment]
Thanks @NAshwini ! any thoughts on when that merge will hit GA?

**Comment by NAshwini** [comment]
Thanks @danielcbright !
Azure chef extension for Linux has been publish today with version "1210.13.2.1".
Soon will be publish it for windows with same version.

**Comment by NAshwini** [comment]
Hi @danielcbright,
It got release with version "1210.13.2.1" https://github.com/chef-partners/azure-chef-extension/releases/tag/1210.13.2.1
