### ISSUE TITLE
Deploy Extension to custom location

### ISSUE THREAD

**Issue by alanhughes10** [chef-partners/azure-chef-extension#272]
## Description

Add the functionality of being able to deploy the Azure Chef Extension to a custom location in Windows and Linux. This can allow for multiple chef configurations while using the same binary. We would do this as a custom extension but came across the Azure limitation of only being able to use 1 custom extension at a time.

## Requirements
* parameterise install location

**Comment by Vasu1105** [comment]
Closing this as this is has azure extension architecture limitations.
