### ISSUE TITLE
Inconsistent behavior with system PATH variable and ruby.exe

### ISSUE THREAD

**Issue by bgs113** [chef-partners/azure-chef-extension#273]
There is an issue when converting a Windows node from using a service to using a scheduled task. The initial extension installation is not adding `C:\opscode\chef\embedded\bin` to the system Path environment variable, and after using Set-AzVMExtension to change the "daemon" setting from "service" to "task", a chef-client scheduled task is created with the following action:

`cmd /c "ruby chef-client -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.13.1.1/chef-client.log -c C:/chef/client.rb"`

This results in failed runs of the task because ruby is not found.

In contrast to this behavior, when performing an initial extension deployment using the "daemon": "task" setting, the chef-client scheduled task is created with the following action and runs successfully:

`cmd /c "C:\opscode\chef\embedded\bin\ruby.exe C:\opscode\chef\bin\chef-client -L C:\chef\chef-client.log -c C:\chef\client.rb"`

Notice that the log location is also different between these scenarios. In all cases, the extension adds `C:\opscode\chef\bin` to the system Path, but not `C:\opscode\chef\embedded\bin` (see Chef requirements here: https://docs.chef.io/install_windows.html#path-system-variable).

**Comment by ayushbhatt29** [comment]
Hello @bgs113, can you please provide more details as where you are getting `ruby is not found` error when tasks are failing, in which log file is this error visible?
 Thank you!

**Comment by dheerajd-msys** [comment]
Fixed via https://github.com/chef-partners/azure-chef-extension/pull/332 and released in `1210.13.4.2`
