### ISSUE TITLE
This should be released to rubygems

### ISSUE THREAD

**Issue by Xorima** [chef-partners/azure-chef-extension#282]
Hi,

I have upgraded from chef 13 to chef 14 on a node, this node has a hard requirement on this `azure-chef-extension` inside the `client.rb` which stops chef from being able to be run on all my nodes

I cannot install the gem from rubygems either because it is not published

Could this be looked into please?

**Comment by Vasu1105** [comment]
If I am correct you want to install azure-chef-extension as gem on the node right ? 
azure-chef-extension can't be installed directly as gem cause it uses different architecture. It uses VM agent for installation process.

**Comment by Xorima** [comment]
Hey,

So I have installed chef via the `azure-chef-extension` and am using the `chef-client` cookbook to upgrade the version of chef from 13 to 14

When this happens it upgrades correctly, however it will then fail to run due to how the `client.rb` has a `require` on `azure-chef-extension` but it is not installed anymore ...

**Comment by Xorima** [comment]
Hey @Vasu1105 is there any chance of an update on this? 

Thanks

**Comment by Vasu1105** [comment]
@Xorima currently I feel you can check by removing or commenting out the require statements in client.rb and then run your chef-client. This is just a workaround for now but it will not anymore use azure-chef-extension as azure-chef-extension is already uninstalled by the chef-client upgrade process. We need to do analysis from our side for this scenario and see how we can handle this in future. But this might take time.

**Comment by Vasu1105** [comment]
@stuartpreston do you have any suggestions here.

**Comment by stuartpreston** [comment]
If you have the chef-client cookbook managing the node, it would also make sense to bring your `client.rb` under complete management and then you can control the timing of the removal of the additional handler lines that are no longer necessary once you have upgraded.

Longer term, I believe we do not need these handlers. They were designed to report status back to Azure, but Microsoft never built the reporting aspect that would have made use of them.
