### ISSUE TITLE
Error during Create action: "Cannot read property 'forEach' of undefined" 

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef-partners/azure-chef-extension#290]
**Describe the bug**
User is attempting to implement the Chef Azure extension following the instructions at

`https://docs.chef.io/azure_portal/`

The user receives the following error when performing step 8

`"Cannot read property 'forEach' of undefined"`

This is occurring across both Linux and Windows extensions.

**To Reproduce**
To reproduce the bug follow the above instructions through step 8.

**Expected behavior**
The expected behavior is that the process continue forward as documented.

**Related Issues**
https://github.com/chef/customer-bugs/issues/141
https://getchef.zendesk.com/agent/tickets/24669

**Comment by davymcaleer** [comment]
@russellseymour can you triage this one please?

**Comment by jgrenoble** [comment]
I noticed this as well, the Azure portal VM extension seems to be missing.

**Comment by Vasu1105** [comment]
@jgrenoble This is issue in relation to Azure portal and we are doing follow up with them. If possible use command line tools to work with azure-chef-extension till that time.

**Comment by OBrienCommaJosh** [comment]
The Azure portal is no longer a supported mechanism for leveraging azure-chef-extension functionality. As @Vasu1105 mentioned, any of the CLI/automation tools that are compatible with azure-chef-extension should be used as alternatives.

Documentation for automation can be found here: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/chef
