### ISSUE TITLE
Extension pinned to now Deprecated Chef Client version

### ISSUE THREAD

**Issue by larry-herz** [chef-partners/azure-chef-extension#291]
Am using the extension for a customer to install the client via AzDo, and with the deprecation of the v14 client, we need a way to get the v15 (or preferably 16) client to install with the extension. I noticed a closed PR from April 2019 stating that the version would be pinned to 14 until 15 was verified with Azure. Are there any plans to allow 15 or 16 to be deployed with this extension?

**Comment by Vasu1105** [comment]
Thank you @larry-herz. Yes we do need to update extension to support 15 and 16 which might take some time.  We will update on this asap.

**Comment by larry-herz** [comment]
As an FYI, I was able to force the installation of 15 (sort of.) We used the "bootstrap_version" to force the installation of the 15.10.12 version of the infra client. Unfortunately, we have not found a good way to add the license acceptance to the client.rb, and apparently that is needed. I already had the default attribute set to accept the license, but until it is added to the client.rb the windows service never successfully checks in with the chef server. Once the chef_license 'accept' Line is added to the client.rb, the client will then pick up and report in to chef, albeit without any environment or runlist information.

**Comment by Vasu1105** [comment]
Yes @larry-herz that's right so this all require code changes to be done.

**Comment by NAshwini** [comment]
Thank you @larry-herz. We have added support for chef-15 in latest release [1210.13.3.1](https://github.com/chef-partners/azure-chef-extension/releases/tag/1210.13.3.1)

**Comment by Vasu1105** [comment]
This release is out so closing it now.
