### ISSUE TITLE
Feature Request: Download Chef from URL in air gapped environments

### ISSUE THREAD

**Issue by trickyearlobe** [chef-partners/azure-chef-extension#297]
**Problem Statement**

- Some customers do not allow their VM's to access the internet
- **azure-chef-extension** currently has 2 mechanisms to perform the chef package install
  - Executing the the omnibus installer scripts from the internet for [linux](https://github.com/chef-partners/azure-chef-extension/blob/350c7b4c90d7ae53ba431c03e09175f96c33049e/ChefExtensionHandler/bin/chef-install.sh#L67) and [windows](https://github.com/chef-partners/azure-chef-extension/blob/350c7b4c90d7ae53ba431c03e09175f96c33049e/ChefExtensionHandler/bin/chef-install.psm1#L86)
  - Perform an install from a package already provided on the local filesystem.

Since there is no internet access, executing the omnibus script from the internet cannot work.

To perform an install with a local package, that package has to be placed onto the system by being baked into the image (which is not an option for retro-fitting Chef to existing machines), or by some other Azure extension. Most customers are already using the **Azure Custom Script** extension for other purposes.

**Proposed Solution**
Add a new parameter called `package_url` which can point to a specific package (.msi .rpm .deb) hosted in the customer Azure subscription which the **azure-chef-extension** can download and subsequently install.

The URL's might look something like `https://my.customer.repo/chef-packages/chef-client-16.rpm` or `https://some.other.customer.repo/chef-stuff/chef-client-16.msi`

**Comment by gsreynolds** [comment]
Resolved by #300
