### ISSUE TITLE
No such file or directory @ rb_sysopen - /etc/chef/client.rb With Chef 16 and Centos 7.7

### ISSUE THREAD

**Issue by jscatala** [chef-partners/azure-chef-extension#302]
Hello!

Currently i'm testing a machine with CentOs 7.7 on azure. When i try to run any bootstrap_version with chef 16 ( i try all versions of chef 16.0.* until 16.2.73.

`
az vm extension set --resource-group RSG  --vm-name MACHINE_NAME   --name LinuxChefClient   --publisher Chef.Bootstrap.WindowsAzure   --version 1210.13 --protected-settings '{"validation_key": "<KEY>"}'   --settings '{ "bootstrap_options": { "chef_server_url": "<URL>", "validation_client_name": "<MACHINE_NAME>" }, "runlist": "role['test']", "environment": "env_name", "CHEF_LICENSE": "accept", "bootstrap_version": "16.2.73"}'
`

> Deployment failed. Correlation ID: <ID>. VM has reported a failure when processing extension 'LinuxChefClient'. Error message: "chef-service enable failed - ["Error enabling chef-client service - No such file or directory @ rb_sysopen - /etc/chef/client.rb - Check log file for details", "error"]"
> More information on troubleshooting is available at https://aka.ms/VMExtensionChefClientLinuxTroubleshoot 

When i look the /etc/chef/ folder, i only found the 0.settings file and nothing else. Sadly no extra information found on the waagent.log . I try with Chef 15.12.22 and seems all OK.

**Comment by Vasu1105** [comment]
Yes this is not the azure-chef-extension issue is the chef-client 16 known-issue. Closing this as we recommend to be on Chef 15 till the Chef 16 gets stable.
