### ISSUE TITLE
Testing azure-chef-extension for chef-16 on Windows 10 pro

### ISSUE THREAD

**Issue by NAshwini** [chef-partners/azure-chef-extension#310]
Azure-chef-extension should be tested with all bootstrap options stated here https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage for chef-16 on Windows 10 pro 1809.

**Comment by ayushbhatt29** [comment]
Tested azure chef extension in windows 10 pro with bootstrap options -[chef_package_path, chef_package_url, run-list, policyfile, daemon] with following commands

**Windows 10 pro 1909** 

-  az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'}, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/15.11.8/windows/10/chef-client-15.11.8-1-x64.msi', 'daemon':'service', 'CHEF_LICENSE':'accept', }"                           
 **RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'}, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/windows/2019/chef-client-16.3.45-1-x64.msi', 'daemon':'service', 'CHEF_LICENSE':'accept', 'runlist' : '[recipe[first::default]]'}"                  
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'},'chef_package_path' : 'C:\chef-client-16.3.45-1-x64.msi', 'daemon':'service', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayush-policy-group', 'policy_name': 'ayupolicy' }}"                            
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/windows/2019/chef-client-16.3.45-1-x64.msi', 'chef_daemon_interval': '18', 'daemon':'none', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayush-policy-group', 'policy_name': 'ayupolicy' }}"                            
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/windows/2019/chef-client-16.3.45-1-x64.msi', 'chef_daemon_interval': '18', 'daemon':'task', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayush-policy-group', 'policy_name': 'ayupolicy' }}                           
 **RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm2" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'test'}, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/windows/2019/chef-client-16.3.45-1-x64.msi', 'daemon':'service', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayush-policy-group', 'policy_name': 'ayupolicy' }, 'environment_variables': {'Path': 'C:/chef','Path' : 'C:/Packages','MESSAGE': 'Testing environment variable update with chef !'}}"                            
**RESULT -- PASS**
