### ISSUE TITLE
Testing azure-chef-extension for chef-16 on ubuntu 16/ ubuntu 20

### ISSUE THREAD

**Issue by NAshwini** [chef-partners/azure-chef-extension#315]
Azure-chef-extension should be tested with all bootstrap options stated here https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage for chef-16 on ubuntu 16/ ubuntu 20

**Comment by sanga1794** [comment]
Tested azure chef extension in ubuntu-16.04 and ubuntu-20.04 with bootstrap options: [chef_package_path, chef_package_url, run-list, policyfile, chef_License, bootstrap_version, bootstrap_channel] with following commands.

**Ubuntu 16.04**

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub16" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'linux' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/16.04/chef_16.3.45-1_amd64.deb', 'CHEF_LICENSE':'accept'}"

- az vm extension set --resource-group "sanga-resource" --vm-name "sanga-ub16" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub1' }, 'bootstrap_version': '16.3.45', 'CHEF_LICENSE':'accept', 'bootstrap_channel':'stable', 'runlist':'[recipe[starter]]' }"

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub16" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'linux1' }, 'chef_package_path' : '/home/sanga/sanga/chef_16.3.45-1_amd64.deb', 'CHEF_LICENSE':'accept'}"

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub3" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'ub3' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/16.04/chef_16.3.45-1_amd64.deb', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'sanga-group', 'policy_name': 'sangapolicy' }}"

- az vm extension set --resource-group "sanga-resource" --vm-name "sanga-ub6" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub5' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/16.04/chef_16.3.45-1_amd64.deb', 'CHEF_LICENSE':'accept', 'environment_variables': {'MESSAGE':'Hello azure chef'} }"

- az vm extension set --resource-group "sanga-resource" --vm-name "sanga-ub6" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub5' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/16.04/chef_16.3.45-1_amd64.deb', 'CHEF_LICENSE':'accept', 'environment_variables': {'MESSAGE':'Hello azure chef'} }"

**Ubuntu 20.04**

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub2" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub1' }, 'bootstrap_version': '16.3.45', 'CHEF_LICENSE':'accept', 'bootstrap_channel':'stable', 'runlist':'[recipe[starter]]' }"

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub22" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub5' }, 'chef_package_path' : '/home/sanga/chef_14.15.6-1_amd64.deb', 'CHEF_LICENSE':'accept', 'runlist':'[recipe[starter]]' }"

- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub20" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'sanga-ub4' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/15.11.8/ubuntu/16.04/chef_15.11.8-1_amd64.deb', 'CHEF_LICENSE':'accept', 'runlist':'[recipe[starter]]' }"
