### ISSUE TITLE
Testing azure-chef-extension for chef-16 on redhat 8.

### ISSUE THREAD

**Issue by NAshwini** [chef-partners/azure-chef-extension#316]
Azure-chef-extension should be tested with all bootstrap options stated here https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage for chef-16 on redhat 8.

**Comment by ayushbhatt29** [comment]
Tested azure chef extension in **Redhat 8** with bootstrap options -[chef_package_path, chef_package_url, run-list, policyfile, daemon] with following commands

**Redhat enterprise linux 8.0**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'bootstrap_version' : '16.3.45' , 'bootstrap_channel' : 'stable', 'CHEF_LICENSE':'accept', 'runlist': '[recipe[new::default]]'}"
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'chef_package_path' : '/home/chef-16.3.45-1.el7.x86_64.rpm ' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' }}"
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/8/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' }}"
**RESULT -- PASS**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'runlist': '[recipe[new::default]]', 'CHEF_LICENSE':'accept'}"
**RESULT -- PASS**
(As no bootstrap version, chef_package_path or chef_package_url is given its installing latest chef-client version as expected.)


- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'bootstrap_version':'15', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' }}"'bootstrap_version':'15', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' }}"
**RESULT -- PASS**
(With  'bootstrap_version':'15' its installing chef-client 15.13.8 as expected)

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/8/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**RESULT -- FAILED**
**Getting the Following ERROR**
```/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1
[Fri Aug 14 11:48:50 UTC 2020] Reading environment variables
Reading chef licence value from settings file
Set CHEF_LICENSE Environment variable as accept
/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1/bin/shared.sh: line 105: python: command not found
  File "/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1/bin/parse_env_variables.py", line 9
    print commands
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(commands)?
[Fri Aug 14 11:48:50 UTC 2020] Environment variables read operation completed
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
SUDO_GID=1000
CHEF_LICENSE=accept
HOSTNAME=ayush-redhat3
OLDPWD=/root
USERNAME=root
SUDO_COMMAND=/bin/bash
USER=root
PWD=/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1
HOME=/root
SUDO_USER=ayushbhatt
SUDO_UID=1000
MAIL=/var/spool/mail/root
TERM=xterm
SHELL=/bin/bash
SHLVL=2
LOGNAME=root
PATH=/opt/chef/bin:/opt/chef/embedded/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
HISTSIZE=1000
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/bin/env
2020-08-14 11:48:52 +0000 extension_root --> /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1
2020-08-14 11:48:52 +0000 Creating EnableChef object with []...
2020-08-14 11:48:52 +0000 Running Chef extension enable command...
2020-08-14 11:48:52 +0000 Node is already registered...
Logging status message: chef-extension enabled
2020-08-14 11:48:52 +0000 Getting chef-client service status
2020-08-14 11:48:52 +0000 chef-client service is already installed.
2020-08-14 11:48:52 +0000 checking if chef-client service interval has been changed by the user...
2020-08-14 11:48:52 +0000 no..chef-client service interval has not been changed by the user..exiting.
Logging status message: chef-service enabled```
