### ISSUE TITLE
Testing azure-chef-extension for chef-16 on redhat 7/ redhat6

### ISSUE THREAD

**Issue by NAshwini** [chef-partners/azure-chef-extension#318]
Azure-chef-extension should be tested with all bootstrap options stated here https://github.com/chef-partners/azure-chef-extension#azure-chef-extension-usage for chef-16 on redhat6 /redhat 7

**Comment by ayushbhatt29** [comment]
Tested azure chef extension in Redhat 6 with following commands

**Redhat enterprise linux 6**

- az vm extension set --resource-group "sanga-resource" --vm-name "sanga-rhel6" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm' , 'CHEF_LICENSE':'accept'}"
**Output - Pass**

- az vm extension set --resource-group "sanga-resource" --vm-name "sanga-rhel" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat1'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'sanga-group', 'policy_name': 'sangapolicy' },'environment_variables': {'MESSAGE':'HELLO CHEF'}}"
**Output - Pass**

Tested azure chef extension in Redhat 7 with following commands

**Redhat enterprise linux 7**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-vm" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat7'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/8/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**Output - Pass**

- az vm extension set --resource-group "ayush-resgrp" --vm-name "redhat7" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': '', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/8/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'runlist': '[recipe[new::default]]'}"
**Output - Pass**
