### ISSUE TITLE
Getting python syntax error for redhat8 for Environment variable option

### ISSUE THREAD

**Issue by NAshwini** [chef-partners/azure-chef-extension#319]
## While passing `'environment_variables': {'abc':'xyz'}` we are getting issue python syntax error may be this is due to `python3`
```
[root@redhat8 Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1]# ./enable.sh 
/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1
[Fri Aug 14 12:38:02 UTC 2020] Reading environment variables
Reading chef licence value from settings file
Set CHEF_LICENSE Environment variable as accept
/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1/bin/shared.sh: line 105: python: command not found
  File "/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.13.4.1/bin/parse_env_variables.py", line 9
    print commands
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(commands)?
[Fri Aug 14 12:38:02 UTC 2020] Environment variables read operation completed
```

This issue was raised here https://github.com/chef-partners/azure-chef-extension/issues/316

**Comment by NAshwini** [comment]
**Done testing on windows 10 pro:**

1) az vm extension set --resource-group "ash-res-grp" --vm-name "win10" --name ChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': 'validation_key', 'client_key': 'clientkey', 'client_rb': ' ~/workspace/chef-repo/.chef/client.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/msys_team', 'chef_node_name': 'win10' }, 'runlist': '[recipe[cbk1::default]]', 'CHEF_LICENSE':'accept','chef_package_url':'https://packages.chef.io/files/stable/chef/16.3.45/windows/2019/chef-client-16.3.45-1-x64.msi', 'environment_variables': {'abc':'xyz'}}"
**Output** :PASS
--
2) az vm extension set --resource-group "ash-res-grp" --vm-name "win11" --name ChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': 'validation_key', 'client_key': 'clientkey', 'client_rb': ' ~/workspace/chef-repo/.chef/client.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/msys_team', 'chef_node_name': 'win11' }, 'CHEF_LICENSE':'accept',, 'environment_variables': {'abc':'xyz'},'custom_json_attr': { 'policy_group': 'azuregrp', 'policy_name': 'azurepolicy' }}"
**Output** :PASS

**Comment by Vasu1105** [comment]
Tested on Windows 2019 with following option 
```
az vm extension set --resource-group "vasurg" --vm-name "vasu-win2019ext" --name "ChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': '/home/msys/workspace/hosted-chef-repo/chef-repo/.chef/client.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/vasuj', 'chef_node_name': 'vj-win2019'},'bootstrap_version' : '16.3.45' , 'bootstrap_channel' : 'stable', 'CHEF_LICENSE':'accept', 'environment_variables': {'MESSAGE': 'Testing environment vars'}, 'runlist': '[recipe[windows_user_privilege::default]]'}"
```
output
```
- Finished ..
  "autoUpgradeMinorVersion": false,
  "forceUpdateTag": null,
  "id": "/subscriptions/91XXXXXXXX/resourceGroups/vasurg/providers/Microsoft.Compute/virtualMachines/vasu-win2019ext/extensions/ChefClient",
  "instanceView": null,
  "location": "eastus",
  "name": "ChefClient",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Chef.Bootstrap.WindowsAzure",
  "resourceGroup": "vasurg",
  "settings": {
    "CHEF_LICENSE": "accept",
    "bootstrap_channel": "stable",
    "bootstrap_options": {
      "chef_node_name": "vj-win2019",
      "chef_server_url": "https://api.chef.io/organizations/vasuj"
    },
    "bootstrap_version": "16.3.45",
    "environment_variables": {
      "MESSAGE": "Testing environment vars"
    },
    "runlist": "[recipe[windows_user_privilege::default]]"
  },
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "1210.13",
  "virtualMachineExtensionType": "ChefClient"
}
```

**Comment by sanga1794** [comment]
**Done testing on Ubuntu:**

**Ubuntu 16.04**
- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub1" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'ub5' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/16.04/chef_16.3.45-1_amd64.deb', 'daemon':'task', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'sanga-group', 'policy_name': 'sangapolicy' },'environment_variables': {'MESSAGE': 'CHEF'}}"

**Ubuntu 18.04**
- az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub18" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'ub7' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/18.04/chef_16.3.45-1_amd64.deb', 'daemon':'task', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'sanga-group', 'policy_name': 'sangapolicy' },'environment_variables': {'MESSAGE': 'CHEF'}}"

**Ubuntu 20.04**
-  az vm extension set --resource-group "SANGA-RESOURCE" --vm-name "sanga-ub21" --name LinuxChefClient --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key': '', 'client_key': '', 'client_rb': '~/chef-repo/.chef/knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/sanga', 'chef_node_name': 'ub3' }, 'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/ubuntu/20.04/chef_16.3.45-1_amd64.deb', 'daemon':'task', 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'sanga-group', 'policy_name': 'sangapolicy' },'environment_variables': {'MESSAGE': 'CHEF'}}"

**Comment by ayushbhatt29** [comment]
Tested on **Redhat enterprise linux**

**Redhat enterprise linux 8.0** 

- az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat8" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/chef_abhatt', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/8/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**OUTPUT -- PASS**

 **Redhat enterprise linux 7.8** 

-  az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat7" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/chef_abhatt', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/7/chef-16.3.45-1.el7.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**OUTPUT -- PASS**

**Redhat enterprise linux 6.7** 

-   az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat7" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/chef_abhatt', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**OUTPUT -- PASS**

**Redhat enterprise linux 6.8** 
-   az vm extension set --resource-group "ayush-resgrp" --vm-name "ayush-redhat7" --name "LinuxChefClient" --publisher Chef.Bootstrap.WindowsAzure --version 1210.13.4.1 --no-auto-upgrade true --protected-settings "{'validation_key':'', 'client_key':'', 'client_rb': 'D:\chef\chef-starter\chef-repo\.chef\knife.rb'}" --settings "{ 'bootstrap_options': { 'chef_server_url': 'https://api.chef.io/organizations/chef_abhatt', 'chef_node_name': 'red-hat'},'chef_package_url' : 'https://packages.chef.io/files/stable/chef/16.3.45/el/6/chef-16.3.45-1.el6.x86_64.rpm' , 'CHEF_LICENSE':'accept', 'custom_json_attr': { 'policy_group': 'ayu-policygroup', 'policy_name': 'ayushpolicy' },'environment_variables': {'MESSAGE':'HELLO'}}"
**OUTPUT -- PASS**
