### ISSUE TITLE
type_handler_version = "1210.13"

### ISSUE THREAD

**Issue by mcalik77** [chef-partners/azure-chef-extension#343]
It is not installing on windows machine if we put the version 1210.13 - It was working fine until 2 days ago. When I tried to deploy with terraform it is not able to install it. If I tried with 1210.12 it is installing.

**Comment by okandamar0610** [comment]
We use terraform resources to install chef_extension. (type_handler_version = "1210.13")

`resource azurerm_virtual_machine_extension chef_extention {
  count = var.chef_extention_enabled ? 1 : 0

  name      = "ChefClient"
  publisher = "Chef.Bootstrap.WindowsAzure"
  type      = "ChefClient"
  
  type_handler_version = "1210.13"
  virtual_machine_id   = azurerm_windows_virtual_machine.virtual_machine.id
`
Had no issue until 3 days ago. Terraform gets stuck when it comes to installing the extension. This is the error code we receive once we troubleshoot inside the VM. 

`ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}
Installing chef from C:\Users\ADMINB~1\AppData\Local\Temp\2\chef-client-17.0.242-1-x64.msi
msiexec was not successful. Received exit code 1603
At line:454 char:5
+     throw "msiexec was not successful. Received exit code $($p.ExitCo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1603:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1603
`

**Comment by ayushbhatt29** [comment]
HI @mcalik77 & @okandamar0610 
This error is coming with latest **Chef Infra Client** version `17.0.242`, we have created an issue for the same  https://github.com/chef/chef/issues/11516.

Meanwhile you can use previous versions of chef client with the help of these options `'bootstrap_version': '16.13.16', 'bootstrap_channel':'stable'` or `'chef_package_url' : 'download url of required chef-client version'` 

Thank you!

**Comment by trickyearlobe** [comment]
See #346

**Comment by ayushbhatt29** [comment]
The PR [#345 ](https://github.com/chef-partners/azure-chef-extension/pull/345) temporarily resolves this issue as we have pinned the extension to chef 16 until chef 17 is tested and verified.

**Comment by okandamar0610** [comment]
Yes, it works. I have added bootstrap version and channel.
```
      "bootstrap_version" : "16.13.16",
      "bootstrap_channel" : "stable",
```

**Comment by TerrieB1** [comment]
Is this now resolved for the customer, please update, thank you

**Comment by ayushbhatt29** [comment]
Hi @okandamar0610, so should we mark this issue as resolved and close it? 

When **chef-17** issue will get resolved we will update on this issue, right now we have pinned the extension to chef 16 so it won't be causing this error even without using `"bootstrap_version"` option.
Thank you

**Comment by okandamar0610** [comment]
Yes, we can mark this issue as resolved. 
Thank you.

**Comment by TerrieB1** [comment]
I am closing this case and ticket 27752.

**Comment by ayushbhatt29** [comment]
Thank you @okandamar0610 and @TerrieB1 closing this issue now.
