### ISSUE TITLE
Installation failure on linux 8+

### ISSUE THREAD

**Issue by skkprogress** [chef-partners/azure-chef-extension#355]
we are currently in a process of upgrading linux version to 8.3.
& we are using Azure extension for install chef-client(version 1210.12) on linux 7+.
When tried to install the same on linux 8.3. Its getting failed with below error. Can you pls. help to suggest a version , that can be used from Linux 8.3 , from Azure chefextension

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionHandlerNonTransientError","message":"The handler for VM extension type 'Chef.Bootstrap.WindowsAzure.LinuxChefClient' has reported terminal failure for VM extension 'LinuxChefExtension' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/install.sh\n[stdout]\n\n\n[stderr]\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/shared.sh: line 5: python: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/shared.sh: line 7: python: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/shared.sh: line 9: python: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/shared.sh: line 11: python: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/shared.sh: line 13: python: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/chef-install.sh: line 119: gem: command not found\n/var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.110.1002/bin/chef-install.sh: line 20: gem: command not found\n'.\r\n \r\n'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/VMExtensionChefClientLinuxTroubleshoot'"}]}`

**Comment by ayushbhatt29** [comment]
Hi @skkprogress, we have worked on similar issue in [334](https://github.com/chef-partners/azure-chef-extension/issues/334), can you please try with `"typeHandlerVersion": "1210.13"`  this will install the latest azure chef extension published i.e - `1210.13.5.2` and let us know if it works.

Thanks and Regards 
Ayush bhatt

**Comment by ayushbhatt29** [comment]
Closing the issue, as solution for similar issue in [334](https://github.com/chef-partners/azure-chef-extension/issues/334)  has been published in chef extension version `1210.13.5.2`. 
Feel free to reopen the issue if it still persists.

Thanks and Regards
Ayush bhatt
