### ISSUE TITLE
Azure extension enable command fails as it takes more that 5 minutes at times

### ISSUE THREAD

**Issue by NimishaS** [chef-partners/azure-chef-extension#47]

**Comment by NimishaS** [comment]
In progress PR: https://github.com/chef-partners/azure-chef-extension/pull/46

**Comment by tekmaven** [comment]
It looks like the PR is closed.  Has this been released to Azure Extensions yet?

**Comment by NimishaS** [comment]
@tekmaven, `azure-chef-extension v1210.12.4.1` has been published and the issue is fixed in it.

**Comment by pennylliang** [comment]
HI @NimishaS 
I am facing this issue in the latest version of chef extension.
Could you help to have a look, I have to use A1 size VM, windows platform.

> [01/13/2016 04:05:49.89] Executing: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\install.cmd 
> [01/13/2016 04:20:50.06] Execution Complete.
> ######
> Execution Output:
> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\ 
> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\ 
> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\
> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000>powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\bin\chef-install.psm1;Install-ChefClient 
> Downloading Chef Client ...
> [01/13/2016 04:17:18] Installing chef...
> Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName          
> -------  ------    -----      ----- -----   ------     -- -----------          
>       0       1      260         68     3     0.00    668 msiexec              
> 
> 
> Execution Error:
> 
> ######
> Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.100.1000\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...

I need to create large number of A1 size VM at the same time, for example 100 vm will easy to reproduce it.

Do I need to open a new issue?
Thanks a lot.
