### ISSUE TITLE
Please add Azure KeyVault support

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#56]
I would like to store my pems in Azure KeyVault and reference them from an ARM template.

**Comment by adamedx** [comment]
@aarsan sounds like a great idea -- what would you expect the input (i.e. the json) to look like for the extension?

**Comment by aarsan** [comment]
Could it look something like this? 

    "protectedSettings": {
        "validation_key_url": "vault.azure.com/my_validation_key_uri
     }

**Comment by coreywagehoft** [comment]
Are there any updates on support for Azure KeyVault?

**Comment by aarsan** [comment]
Any chance this can get implemented?

**Comment by karstenmueller** [comment]
I second this request;)

**Comment by stuartpreston** [comment]
Closing this - this is already possible using ARM - see https://www.jamesbannanit.com/2017/03/store-chef-organization-certificate-azure-key-vault/
