### ISSUE TITLE
Adding "environment" to the bootstrap_options in the ARM template doesn't seem to do anything.

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#58]
The bootstrap options in my ARM template appears to be ignoring the "environment" property. 

"bootstrap_options": {
            "environment": "[parameters('chef_env')]",
            "chef_node_name": "[parameters('chef_node_name')]",
            "chef_server_url": "[parameters('chef_server_url')]",
            "validation_client_name": "[parameters('validation_client_name')]"
          }

**Comment by NimishaS** [comment]
@aarsan , this issue has been fixed here: https://github.com/chef-partners/azure-chef-extension/issues/50, but not released yet. I am closing this issue and keeping https://github.com/chef-partners/azure-chef-extension/issues/50 open till the fix is not released.
