### ISSUE TITLE
How to set the chef run interval frequency

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#60]
I would like to be able to set the Chef run frequency without having to run a separate cookbook (chef-client) to do so. It would be extremely helpful if the interval and play settings were included in this extension. Is this something that is there which I may have overlooked?

**Comment by NimishaS** [comment]
@aarsan, for windows we have a service running that runs `chef-client` after every 30 minutes. For linux, there a cronjob that does the same thing. This interval is not configurable though.
Does that answer you?

**Comment by aarsan** [comment]
I'm not sure what process is used to initialize the service but from the cli in Windows, you can install the service by typing 'chef-service-manager', which creates the service. That service runs the following command:

    "C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\bin\chef-windows-service" -c C:\chef\client.rb -L C:\chef\chef-client.log"

If I manually edit that command (in the registry) and add an interval "...chef-windows-service" -i 60 -c C:\chef ...", I now have client runs every 60 seconds. If that interval switch is left out, it runs every 1800 seconds (30 minutes). 

I don't know if there is a way to pass in that interval during the installation (i'm looking into this) but there is a way to modify the interval via the registry. It would be extremely helpful to be able to set this upon enabling the chef extension. If I can find a way to do this on installation, I will put in a pull request.

**Comment by NimishaS** [comment]
We are also using `chef-service-manager` to initialize the service in windows. This is taken care of by the extension itself. User doesn't need to do any setting for this.
We'll discuss with chef team about making this `interval` configurable.

**Comment by aarsan** [comment]
Do you have an update on this?

**Comment by EmFl** [comment]
Could it also be possible to prevent the service from being created to allow chef runs to be manually started ?

**Comment by EmFl** [comment]
I ran chef-servive-manager -a uninstall to remove the chef-client service on all my vms and found out that a few hours later all my services were installed back with chef-client being run every 30 minutes ...

**Comment by cedwards-reisys** [comment]
Would like the ability to have chef-client run frequency to be just once.  So no interval at all.

**Comment by Aliasgar16** [comment]
We have fixed this in the latest extension version `1210.12.106.1000`.
