### ISSUE TITLE
Documentation to use PowerShell to Setup VM (CentOS) 

### ISSUE THREAD

**Issue by ArneCoder** [chef-partners/azure-chef-extension#72]
Is there somewhere an documentation how to setup an new Linux VM via PowerShell or AZURE-CLI with Chef-Extension enabled ?

Regarding this issue: https://github.com/chef-partners/azure-chef-extension/issues/17 
CentOS is now supported? Would be great if someone could provide some kind of documentation.

**Comment by tmaierACN** [comment]
I am also interested in this matter. I was not able to use it successfully up to now. (Chef 12, CentOS 7)

**Comment by tmaierACN** [comment]
@ArneCoder , please see https://github.com/chef-partners/azure-chef-extension/issues/73#issuecomment-145592093

**Comment by siddheshwar-more** [comment]
@ArneCoder @tmaierACN - we are working on documentation!

**Comment by NimishaS** [comment]
@ArneCoder , the document has been updated. Please refer https://github.com/chef-partners/azure-chef-extension#azure-chef-extension
