### ISSUE TITLE
Unexpected release of Chef VM Extension 1210.12.5.1000 means no way to build machines with ChefClient 12.4.x

### ISSUE THREAD

**Issue by stuartpreston** [chef-partners/azure-chef-extension#83]
I can see the new version of the extension 1210.12.5.1000 has been deployed which decouples the extension from the ChefClient payload:

```
Type             Version
----             -------
CentosChefClient 11.12.4.2
CentosChefClient 11.14.6.1
ChefClient       11.10.4
ChefClient       11.12.0.0
ChefClient       11.18.6.2
ChefClient       1205.12.2.1
ChefClient       1207.12.3.0
ChefClient       1210.12.4.1000
ChefClient       1210.12.5.1000
LinuxChefClient  11.18.6.2
LinuxChefClient  1201.12.1.1
LinuxChefClient  1205.12.2.1
LinuxChefClient  1207.12.3.0
LinuxChefClient  1210.12.4.2000
LinuxChefClient  1210.12.5.1000
```

However, in an ARM template it is not possible to specify the build and revision number hence the latest build is still specified as version '1210.12'.  The net result is that the most recent release of the VM extension means the non-decoupled style of deployment can no longer be achieved for new machines, and therefore I can no longer build a machine with ChefClient 12.4.x

**Suggestion:** 
1) Yank the 1210.12.5.1000 release so that the behaviour seen is documented/expected
2) Build a new VM Extension with a new Major version number (e.g. something like 1251.0 or anything higher than 1210) so it:
- requires people to **choose** whether to upgrade to it rather than being forced to take it if they rebuild their machines using the same template
- differentiates this build of the extension from the previous 1210.12 build

3) Parameterise the ChefClient build number so it can be passed to OmniTruck and people can override it in publicSettings.config - unless I am reading https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.psm1#L81-L82 incorrectly?

Related: #81 #75

**Comment by NimishaS** [comment]
@stuartpreston , we are adding support to specify `chef-client` version through `knife-azure`, `powershell cli` and `xplat cli` for the extension. Currently we are in process of adding option in `knife-azure` for `chef-client` version. This will work for `ubuntu` and `centos`. For `windows` we are facing some challenges.
We'll eventually support other tools too.

**Comment by stuartpreston** [comment]
I'm specifically talking about ARM, where our only option at the moment is through the publicSettings and privateSettings.config - will the config value be able to be specified in one of these?  Thanks.

**Comment by NimishaS** [comment]
Yes `chef-client` version can be specified in publicsettings file.

**Comment by stuartpreston** [comment]
Thanks, I'll try this out when I next see the extension updated.
