### ISSUE TITLE
Please add a client location parameter

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#85]
It would be very helpful if I could host my own client in blob storage and reference that location in the ARM template.

**Comment by aarsan** [comment]
is this possible yet?

**Comment by adamedx** [comment]
Not sure what you mean by "client":

* The `client.rb` file?
* The actual chef-client executable software?
* The validator or other key used to authenticate against the Chef Server?

The second thing above is probably doable today using the `knife bootstrap azure` subcommand which uses the template.

**Comment by aarsan** [comment]
The msi file to install the chef client

**Comment by stuartpreston** [comment]
Closing this issue due to age, we continue to require internet access to deploy the MSI with no changes planned.  We are hoping to shrink the payload down so that we can embed it in the Extension again.
